### ISSUE TITLE
[TM]: IOTM launcher icons "dissappear"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.11#22]
added icons to IOTM reported to disappear when laucnhed:
https://forums.mauilinux.org/showthread.php?tid=23918

**Comment by eikehein** [comment]
I've heard something like this before a few weeks ago in passing, and it was also about Chromium. Has to be specific to it somehow. I'll try to find out.

**Comment by eikehein** [comment]
I can't reproduce this with Fedora's Chromium, but the problem can be distro/package-specific (.desktop file names etc). I'll check with a Maui VM soon.

**Comment by eikehein** [comment]
I haven't been able to reproduce this with Maui and Maui's Chromium package in a VM yet either, but still having an eye out for it.
