### ISSUE TITLE
[kamoso 3.2]: video is choppy

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.11#5]
on same computer, cheese does a much smoother video, while kamoso looks like 2-3 frames per second.
Eventually the algorythm or format could be changed, like in vokoscreen, some codecs do choppy videos while other formats (mkv) do result in a much smoother video taken fullscreen.

**Comment by aleixpol** [comment]
I've been looking into it. I'm trying to figure out what's exactly the problem, as it looks ok here.
Do you think you could give me the codecs information of the files you get? VLC exposes such information:
http://i.imgur.com/LM67HLG.png
