### ISSUE TITLE
widgets: "disk quota" missing picture

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.11#61]
![screenshot_20170215_143407](https://cloud.githubusercontent.com/assets/840070/22976659/00fe8d2e-f38c-11e6-93df-2c6b194f485f.png)

**Comment by notmart** [comment]
drawn a picture for it, asking the breeze icons maintainer to include it

**Comment by star-buck** [comment]
@notmart : did it got accepted? what release would this be in?

**Comment by notmart** [comment]
it has got accepted and has been releases in frameworks 5.32, on 11th of march

**Comment by star-buck** [comment]
no icon in kde neon 5.10 beta
