### ISSUE TITLE
wallpaper dialog: scrolling down one inch via mousewheel jumps all the way up instead of further scrolling down

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.11#68]
https://www.dropbox.com/s/vhjicllmidte6rv/wallpaper-mousescroll-jumps%20back%20to%20top.mkv?dl=0

mousewheel UP scrolling goes smoothly up though, just if you are already down in the list due to the selected wallpaper, scrolling further down via mousewheel makes the list glitch to the top.

**Comment by notmart** [comment]
managed to reproduce, it seems to happen exactly the first time the view is scrolled after the window has been opened and exactly once, seems be an issue in the ScrollView component of QtQuickControls1, will see if it's an easy fix, otherwise will have to go for a different implementation, maybe qtquickcontrols2 based

**Comment by notmart** [comment]
upstream bug: https://bugreports.qt.io/browse/QTBUG-59633
possible patch: https://codereview.qt-project.org/#/c/189158/

**Comment by star-buck** [comment]
oddly on current netrunner ISO scrolling UP now doesnt even work anymore, simply nothing happens.
Scrolling down jumps all the way up as usual.
Maybe the "selected item" marker while visually looks correct still is still stuck on the first wallpaper internally?

**Comment by notmart** [comment]
https://codereview.qt-project.org/#/c/189158/ has been merged now: @apachelogger @shadeslayer could the patch be applied to qt in either neon or netrunner?

**Comment by hsitter** [comment]
https://packaging.neon.kde.org/qt/qtquickcontrols.git/commit/?h=Neon/release&id=21e789e39263ce1e6f27fbde55b08ce7b0308044

**Comment by notmart** [comment]
for widespread release, it should be in Qt 5.9 that will happen on 31st of may

**Comment by notmart** [comment]
rlease schedule https://wiki.qt.io/Qt_5.9_Release
